services:
  postgres:
    image: postgres:latest
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-server
    environment:
      - SERVER_PORT:3001
      - DATABASE_URL:${DATABASE_URL}
    ports:
      - "${SERVER_PORT}:3001"
    depends_on:
      - postgres
    networks:
      - app_network
    volumes:
      - .:/app

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
